version: '3.8'

services:
  db:
    image: felipealonso23/obligatorio:v1
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306

volumes:
  mysql_data: